version: '3'
services:
  kafka:
    image: blacktop/kafka:1.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CREATE_TOPICS=bro:1:1:compact
  kibana:
    depends_on:
      - elasticsearch
    image: blacktop/kibana:5.6
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  bro:
    depends_on:
      - kafka
    build: ./kafka
    image: blacktop/bro:kafka
    links:
      - kafka:localhost
    volumes:
      - ./pcap:/pcap
    command: -F -r heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }"
