version: '3'
services:
  kafka:
    image: blacktop/kafka:0.11
    ports:
      - "9092:9092"
    networks:
      - kafnet
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=bro:1:1
  bro:
    depends_on:
      - kafka
    build: ./kafka
    image: blacktop/bro:kafka
    networks:
      - kafnet
    links:
      - kafka
    volumes:
      - ./pcap:/pcap
    command: -F -r heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }"
  consumer:
    depends_on:
      - kafka
    build: ./tests/kafka-tools
    image: blacktop/ktools:latest
    networks:
      - kafnet
    links:
      - kafka

networks:
  kafnet:
    driver: bridge
