version: '3'
services:
  zookeeper:
    image: blacktop/kafka:0.11
    ports:
      - "2181:2181"
    command: zookeeper-server-start.sh config/zookeeper.properties
  kafka:
    image: blacktop/kafka:0.11
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CREATE_TOPICS=bro:1:1
  bro:
    depends_on:
      - kafka
    build: ./kafka
    image: blacktop/bro:kafka
    links:
      - kafka:localhost
    volumes:
      - ./pcap:/pcap
    command: -F -r heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }"
