version: '3'
services:
  redis:
    image: redis:alpine
  elasticsearch:
    image: blacktop/elasticsearch:5.6
    ports:
      - "9200:9200"
  kibana:
    image: blacktop/kibana:5.6
    ports:
      - "80:5601"
    links:
      - elasticsearch
  logstash:
    depends_on: kibana
    image: blacktop/logstash:5.6
    links:
      - redis
      - elasticsearch
    command: |
      logstash -e 'input {
                     redis {
                       host => "redis"
                       data_type => "list"
                       db => 3
                       key => "bro*"
                       codec => "json"
                     }
                   }
                   output {
                     elasticsearch {
                       hosts => "elasticsearch:9200"
                     }
                   }'
  bro:
    build: ./redis
    image: blacktop/bro:redis
    links:
      - redis
    volumes:
      - ./pcap:/pcap
    command: -F -r heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }"
